// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXuDt0YUR_RSf-CQvTJ83eD7Ar_YS6F4M',
    appId: '1:41979913328:web:47c945cbc0b864aa7fc0b5',
    messagingSenderId: '41979913328',
    projectId: 'al-maskan',
    authDomain: 'al-maskan.firebaseapp.com',
    storageBucket: 'al-maskan.firebasestorage.app',
    measurementId: 'G-4CCC3GNWBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Ncq1IZZSPOZOowRIx9KyTjJrb67HEFQ',
    appId: '1:41979913328:android:53e17541918463bd7fc0b5',
    messagingSenderId: '41979913328',
    projectId: 'al-maskan',
    storageBucket: 'al-maskan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp-cxXhjJhRoRGOqqk8hGaHQuidoUVkVA',
    appId: '1:41979913328:ios:ac74ec438f402e627fc0b5',
    messagingSenderId: '41979913328',
    projectId: 'al-maskan',
    storageBucket: 'al-maskan.firebasestorage.app',
    iosBundleId: 'com.example.almaskan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp-cxXhjJhRoRGOqqk8hGaHQuidoUVkVA',
    appId: '1:41979913328:ios:ac74ec438f402e627fc0b5',
    messagingSenderId: '41979913328',
    projectId: 'al-maskan',
    storageBucket: 'al-maskan.firebasestorage.app',
    iosBundleId: 'com.example.almaskan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXuDt0YUR_RSf-CQvTJ83eD7Ar_YS6F4M',
    appId: '1:41979913328:web:575c2c264e69bc207fc0b5',
    messagingSenderId: '41979913328',
    projectId: 'al-maskan',
    authDomain: 'al-maskan.firebaseapp.com',
    storageBucket: 'al-maskan.firebasestorage.app',
    measurementId: 'G-X4GB8SSRRP',
  );
}
